name: 'Cypress tests'

on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          git clone https://gitlab.com/sendcloud-public/crispy-succotash.git
          docker-compose up -d
      - run: npm install
      - run: npm run test
